import { recommend } from './engine.js';

const CFG='netflick-config-v1', CACHE='netflick-players-v1', SESSION='netflick-session-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={players:[],selected:new Set(),setupCourts:2,session:null,lastUndo:null,demo:false,lineupSelected:new Set()};
const demoPlayers=[
  ['leo','Leo','Male','A'],['verry','Verry','Male','A'],['andi','Andi G','Male','B'],['charles','Charles','Male','B'],['edric','Edric','Male','C'],['richo','Richo','Male','C'],['levina','Levina','Female','A'],['lysa','Lysa','Female','A'],['tesa','Tesa','Female','B'],['vita','Vita','Female','B'],['gaby','Gaby','Female','C'],['ririn','Ririn','Female','C']
].map(([id,name,gender,level])=>({id,name,gender,level,active:true,incomplete:false}));

function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function cfg(){return read(CFG)}
function setView(id){['connect-view','setup-view','live-view'].forEach(x=>$('#'+x).hidden=x!==id);$('#new-session').hidden=id!=='live-view'}
function validSession(s){return s&&s.version===1&&Number.isInteger(s.courts)&&Array.isArray(s.roster)}
function toast(text,undo){const t=$('#toast');t.innerHTML=undo?`${text} · <button id="undo-toast" class="text-button">Undo</button>`:text;t.classList.add('show');if(undo)$('#undo-toast').onclick=()=>{undo();t.classList.remove('show')};clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500)}
function initials(name){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function timeAgo(ts){if(!ts)return'';const s=Math.floor((Date.now()-ts)/1000);if(s<45)return'just now';const m=Math.floor(s/60);if(m<60)return`${m}m ago`;return`${Math.floor(m/60)}h ago`}
function recKey(rec){return rec?rec.matches.map(m=>m.players.map(p=>p.playerId).sort().join(',')).sort().join('|'):null}
async function api(path,opts={}){const c=cfg();if(!c)throw Error('Not connected');const r=await fetch(c.url.replace(/\/$/,'')+path,{...opts,headers:{'content-type':'application/json','x-app-key':c.key,...opts.headers}});let body={};try{body=await r.json()}catch{}if(!r.ok)throw Error(body.error||`Request failed (${r.status})`);return body}
function cachePlayers(players){state.players=players;write(CACHE,{syncedAt:Date.now(),players})}
async function loadPlayers(){if(state.demo){cachePlayers(demoPlayers);return}const cached=read(CACHE);if(cached?.players)state.players=cached.players;const body=await api('/api/players');cachePlayers(body.players)}

function renderPicker(){const q=$('#player-search').value.trim().toLowerCase();const list=state.players.filter(p=>p.name.toLowerCase().includes(q));$('#player-picker').innerHTML=list.map(p=>`<button class="picker ${state.selected.has(p.id)?'selected':''} ${p.incomplete?'incomplete':''}" data-pick="${p.id}" aria-pressed="${state.selected.has(p.id)}"><span class="avatar">${initials(p.name)}</span><span><strong>${p.name}</strong><small>${p.gender||'Gender missing'} · ${p.level?`Level ${p.level}`:'Level missing'}</small></span></button>`).join('')||'<p class="muted">No players found.</p>';$$('[data-pick]').forEach(b=>b.onclick=()=>{const p=state.players.find(x=>x.id===b.dataset.pick);if(p.incomplete){openPlayerDialog(p);return}state.selected.has(p.id)?state.selected.delete(p.id):state.selected.add(p.id);renderPicker();renderSetupMeta()})}
function renderSetupMeta(){const selected=[...state.selected].map(id=>state.players.find(p=>p.id===id)).filter(Boolean);$('#setup-courts').textContent=state.setupCourts;$('#selected-count').textContent=`${selected.length} selected`;$('#capacity-note').textContent=`${state.setupCourts*4} playing spots · ${selected.length} players selected`;const eligible=selected.filter(p=>!p.incomplete);const warnings=[];if(eligible.length<4)warnings.push('Select at least 4 complete players.');if(eligible.length<state.setupCourts*4)warnings.push(`Only ${Math.floor(eligible.length/4)} court(s) can be filled by headcount.`);$('#setup-warning').textContent=warnings.join(' ');$('#start-session').disabled=eligible.length<4;renderPicker()}
function showSetup(){setView('setup-view');renderSetupMeta()}

function newSession(){if(state.session&&!confirm('End this session and clear tonight’s counters?'))return;localStorage.removeItem(SESSION);state.session=null;state.selected=new Set();showSetup()}
function startSession(){const roster=[...state.selected].map(id=>state.players.find(p=>p.id===id)).filter(p=>p&&!p.incomplete).map(p=>({playerId:p.id,name:p.name,gender:p.gender,level:p.level,count:0,status:'playing'}));state.session={version:1,sessionId:crypto.randomUUID(),startedAt:new Date().toISOString(),courts:state.setupCourts,roster,lastRecommendation:null};saveSession();renderLive()}
function saveSession(){write(SESSION,state.session)}
function minActiveCount(){const a=state.session.roster.filter(p=>p.status!=='benched');return a.length?Math.min(...a.map(p=>p.count)):0}
function summary(){const a=state.session.roster.filter(p=>p.status!=='benched'),b=state.session.roster.length-a.length,counts=a.map(p=>p.count),min=counts.length?Math.min(...counts):0,max=counts.length?Math.max(...counts):0;return[{v:a.length,l:'Active'},{v:b,l:'Benched'},{v:`${min}–${max}`,l:'Play range'},{v:max-min,l:'Fairness gap'}]}
function renderTeam(team){return `<div class="team">${team.map(p=>`<strong>${p.name}</strong>`).join('')}<small>${team.map(p=>p.level).join('')} · counts ${team.map(p=>p.count).join('/')}</small></div>`}
function renderLive(){setView('live-view');const s=state.session;$('#live-courts').textContent=`${s.courts} court${s.courts===1?'':'s'}`;$('#session-title').textContent=new Date(s.startedAt).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'});$('#summary').innerHTML=summary().map(x=>`<div class="summary-item"><strong>${x.v}</strong><span>${x.l}</span></div>`).join('');const rec=recommend(s.roster,s.courts);s.lastRecommendation=rec;saveSession();$('#recommendations').innerHTML=rec.matches.length?rec.matches.map(m=>`<article class="court-card"><div class="court-head"><div><strong>Court ${m.court}</strong> <span class="court-type">${m.type}</span></div><button type="button" class="court-edit" data-edit-court="${m.court}" aria-label="Edit Court ${m.court} lineup">✎</button></div><div class="teams">${renderTeam(m.teamA)}<span class="versus">VS</span>${renderTeam(m.teamB)}</div><p class="why">Level gap ${m.levelGap} · selected from the lowest available counts</p><button class="played" data-played="${m.court}">Played · +1 all</button></article>`).join(''):`<div class="empty-state"><strong>No legal court yet.</strong><br>${rec.incomplete.length?'Complete missing Gender or Level.':'The available gender mix cannot form MD, WD, or XD.'}</div>`;$$('[data-played]').forEach(b=>b.onclick=()=>played(rec.matches.find(m=>m.court===Number(b.dataset.played)),b));$$('[data-edit-court]').forEach(b=>b.onclick=()=>{const m=rec.matches.find(x=>x.court===Number(b.dataset.editCourt));openLineupDialog(m?m.players.map(p=>p.playerId):[],`Court ${b.dataset.editCourt} lineup`)});const wait=[...rec.waiting,...rec.incomplete];$('#waiting').innerHTML=wait.length?`<strong>Waiting (${wait.length})</strong><br>${wait.map(p=>p.name).join(' · ')}${rec.incomplete.length?'<br><small>Incomplete players are not eligible until corrected.</small>':''}`:'';renderLedger()}
function playerRow(p){return `<div class="player-row ${p.status==='benched'?'benched':''}"><div class="player-meta"><strong>${p.name}</strong><small>${p.gender} · Level ${p.level}${p.lastUpdated?` · ${timeAgo(p.lastUpdated)}`:''}</small></div><div class="count-controls"><button data-count="${p.playerId}" data-delta="-1" aria-label="Subtract one game from ${p.name}">−</button><output aria-label="${p.name} has played ${p.count} games">${p.count}</output><button data-count="${p.playerId}" data-delta="1" aria-label="Add one game to ${p.name}">+</button></div><button class="bench" data-bench="${p.playerId}" aria-label="${p.status==='benched'?'Return':'Bench'} ${p.name}">${p.status==='benched'?'Return':'Bench'}</button></div>`}
function renderLedger(){const q=$('#ledger-search').value.trim().toLowerCase();const rows=[...state.session.roster].filter(p=>p.name.toLowerCase().includes(q)).sort((a,b)=>a.count-b.count||a.name.localeCompare(b.name));const playing=rows.filter(p=>p.status!=='benched'),benched=rows.filter(p=>p.status==='benched');$('#ledger').innerHTML=(playing.length?`<div class="ledger-group"><p class="ledger-group-head">Playing (${playing.length})</p>${playing.map(playerRow).join('')}</div>`:(q?'<p class="muted">No players match.</p>':''))+(benched.length?`<details class="ledger-group"${playing.length?'':' open'}><summary class="ledger-group-head">Benched (${benched.length})</summary>${benched.map(playerRow).join('')}</details>`:'');$$('[data-count]').forEach(b=>b.onclick=()=>adjustCount(b.dataset.count,Number(b.dataset.delta)));$$('[data-bench]').forEach(b=>b.onclick=()=>toggleBench(b.dataset.bench))}
function adjustCount(id,d){const p=state.session.roster.find(x=>x.playerId===id);p.count=Math.max(0,p.count+d);p.lastUpdated=Date.now();saveSession();renderLive()}
function toggleBench(id){const p=state.session.roster.find(x=>x.playerId===id);p.status=p.status==='benched'?'playing':'benched';saveSession();renderLive()}
function playedIds(ids){const roster=state.session.roster;const before=ids.map(id=>({id,count:roster.find(x=>x.playerId===id).count}));ids.forEach(id=>{const r=roster.find(x=>x.playerId===id);r.count++;r.lastUpdated=Date.now()});saveSession();renderLive();toast('Four counts updated',()=>{before.forEach(x=>roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()})}
function played(match,button){if(!match||button.disabled)return;button.disabled=true;playedIds(match.players.map(p=>p.playerId))}

function openLineupDialog(prefillIds,title){state.lineupSelected=new Set(prefillIds);$('#lineup-dialog-title').textContent=title||'Log a match';$('#lineup-search').value='';$('#lineup-error').textContent='';renderLineupPicker();$('#lineup-dialog').showModal()}
function renderLineupPicker(){const q=$('#lineup-search').value.trim().toLowerCase();const eligible=state.session.roster.filter(p=>p.status!=='benched'&&p.name.toLowerCase().includes(q));$('#lineup-picker').innerHTML=eligible.map(p=>`<button type="button" class="picker ${state.lineupSelected.has(p.playerId)?'selected':''}" data-lineup-pick="${p.playerId}" aria-pressed="${state.lineupSelected.has(p.playerId)}"><span class="avatar">${initials(p.name)}</span><span><strong>${p.name}</strong><small>${p.gender||'Gender missing'} · ${p.level?`Level ${p.level}`:'Level missing'} · ${p.count} played</small></span></button>`).join('')||'<p class="muted">No players found.</p>';$$('[data-lineup-pick]').forEach(b=>b.onclick=()=>{const id=b.dataset.lineupPick;if(state.lineupSelected.has(id))state.lineupSelected.delete(id);else{if(state.lineupSelected.size>=4){toast('Only 4 players can play a court');return}state.lineupSelected.add(id)}renderLineupPicker()});$('#lineup-count').textContent=`${state.lineupSelected.size} of 4 selected`;$('#lineup-confirm').disabled=state.lineupSelected.size!==4}

function openPlayerDialog(player=null){$('#player-dialog-title').textContent=player?'Edit player':'Add player';$('#edit-player-id').value=player?.id||'';$('#player-name').value=player?.name||'';$('#player-gender').value=player?.gender||'';$('#player-level').value=player?.level||'';$('#player-error').textContent='';$('#player-dialog').showModal()}
async function savePlayer(e){e.preventDefault();const id=$('#edit-player-id').value;const input={name:$('#player-name').value.trim(),gender:$('#player-gender').value,level:$('#player-level').value};if(!input.name||!input.gender||!input.level){$('#player-error').textContent='Name, Gender, and Level are required.';return}const dup=state.players.find(p=>p.id!==id&&p.name.trim().toLowerCase()===input.name.toLowerCase());if(dup&&!confirm(`${dup.name} already exists. Create another player with this name?`))return;$('#save-player').disabled=true;try{let saved;if(state.demo){saved={id:id||crypto.randomUUID(),...input,active:true,incomplete:false}}else saved=await api(id?`/api/players/${id}`:'/api/players',{method:id?'PATCH':'POST',body:JSON.stringify(input)});const i=state.players.findIndex(p=>p.id===saved.id);if(i>=0)state.players[i]=saved;else state.players.push(saved);cachePlayers(state.players);if(state.session){const existing=state.session.roster.find(p=>p.playerId===saved.id);if(existing){Object.assign(existing,{name:saved.name,gender:saved.gender,level:saved.level})}else state.session.roster.push({playerId:saved.id,name:saved.name,gender:saved.gender,level:saved.level,count:minActiveCount(),status:'playing',lastUpdated:Date.now()});saveSession();renderLive()}else{state.selected.add(saved.id);renderSetupMeta()}$('#player-dialog').close();toast(id?'Player updated':'Player added')}catch(err){$('#player-error').textContent=err.message}finally{$('#save-player').disabled=false}}
async function boot(){const s=read(SESSION);if(validSession(s)){state.session=s;renderLive();return}if(!cfg()){setView('connect-view');return}try{await loadPlayers();showSetup()}catch{const cached=read(CACHE);if(cached?.players){state.players=cached.players;showSetup();toast('Offline · using saved players')}else setView('connect-view') }}

$('#connect').onclick=async()=>{const url=$('#worker-url').value.trim(),key=$('#app-key').value.trim();if(!url||!key)return;write(CFG,{url,key});try{await loadPlayers();showSetup()}catch(e){localStorage.removeItem(CFG);$('#connect-error').textContent=e.message}};
$('#demo').onclick=async()=>{state.demo=true;await loadPlayers();showSetup()};
$('#player-search').oninput=renderPicker;$('#ledger-search').oninput=renderLedger;$$('[data-court-delta]').forEach(b=>b.onclick=()=>{state.setupCourts=Math.max(1,Math.min(10,state.setupCourts+Number(b.dataset.courtDelta)));renderSetupMeta()});$$('[data-live-court-delta]').forEach(b=>b.onclick=()=>{state.session.courts=Math.max(1,Math.min(10,state.session.courts+Number(b.dataset.liveCourtDelta)));saveSession();renderLive()});
$('#start-session').onclick=startSession;$('#new-session').onclick=newSession;$('#open-add-player').onclick=()=>openPlayerDialog();$('#live-add-player').onclick=()=>openPlayerDialog();$('#refresh-recommendation').onclick=()=>{const before=recKey(state.session.lastRecommendation);renderLive();const after=recKey(state.session.lastRecommendation);toast(before===after?'Refreshed · same match-up (no counts changed)':'Refreshed · new match-up')};$('#log-custom-match').onclick=()=>openLineupDialog([],'Log a custom match');$('#lineup-search').oninput=renderLineupPicker;$('#lineup-confirm').onclick=()=>{if(state.lineupSelected.size!==4){$('#lineup-error').textContent='Pick exactly 4 players.';return}playedIds([...state.lineupSelected]);$('#lineup-dialog').close()};$('#player-form').addEventListener('submit',savePlayer);$$('[data-close-dialog]').forEach(b=>b.onclick=()=>{$('#player-dialog').close();$('#lineup-dialog').close()});
setInterval(()=>{if(state.session&&!$('#live-view').hidden)renderLedger()},30000);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
boot();