import { recommend, PARTITIONS, strength, lineupType, roundRole, roundTier } from './engine.js';
import { FOCUS, MAX_FOCUS, ERROR_SOURCES, CAUSES, blankGame, localDate, localTime, summarize, suggestFocus, focusLabel, sourceLabel, causeLabel, sides, INTENSITY, toMarkdown, obsidianUrl, noteName } from './mylog.js';

const CFG='netflick-config-v1', CACHE='netflick-players-v1', SESSION='netflick-session-v1', DEMO='netflick-demo-v1', ME='netflick-me-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={players:[],rosterPick:new Set(),syncing:false,session:null,lastUndo:null,demo:false,lineupSelected:new Set(),lineupCourt:null,lineupPartition:0,openCards:new Set(),meDraft:null,meUndo:null};
const demoPlayers=[
  ['leo','Leo','Male','A'],['verry','Verry','Male','A'],['andi','Andi G','Male','B'],['charles','Charles','Male','B'],['edric','Edric','Male','C'],['richo','Richo','Male','C'],['levina','Levina','Female','A'],['lysa','Lysa','Female','A'],['tesa','Tesa','Female','B'],['vita','Vita','Female','B'],['gaby','Gaby','Female','C'],['ririn','Ririn','Female','C']
].map(([id,name,gender,level])=>({id,name,gender,level,active:true,incomplete:false}));

function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function cfg(){return read(CFG)}
function setView(id){['connect-view','live-view'].forEach(x=>$('#'+x).hidden=x!==id);const s=state.session;$('#new-session').hidden=!(id==='live-view'&&s&&(s.roster.length||s.rounds.length))}
function esc(t){return String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function blankMe(){return{games:[],focusIn:(meCfg().lastFocus?.items)||[],focusHit:{},focusNext:[],energy:null,intensity:null,worked:'',exportedAt:null}}
function blankSession(){return{version:2,sessionId:crypto.randomUUID(),startedAt:Date.now(),courts:0,roster:[],rounds:[],courtState:{},lastRecommendation:null,me:blankMe()}}
function ensureSession(){if(!state.session){state.session=blankSession();saveSession()}}
function validSession(s){return s&&(s.version===1||s.version===2)&&Number.isInteger(s.courts)&&Array.isArray(s.roster)}
function migrateSession(s){if(s.version===1){s.version=2;s.rounds=[];s.courtState={}}s.rounds=s.rounds||[];s.courtState=s.courtState||{};s.me={...blankMe(),...(s.me||{})};return s}
function meCfg(){return read(ME,{})||{}}
function setMeCfg(patch){write(ME,{...meCfg(),...patch})}
const ROLE_LABEL={carry:'Carry',intensity:'Intensity',light:'Light'};
function nameOf(id){const r=state.session.roster.find(p=>p.playerId===id);return r?r.name:'Unknown'}
function busyIds(){return new Set(Object.values(state.session.courtState).flatMap(o=>[...o.teamA,...o.teamB].map(p=>p.id)))}
function courtOf(id){for(const[c,o]of Object.entries(state.session.courtState))if([...o.teamA,...o.teamB].some(p=>p.id===id))return Number(c);return null}
function emptyCourts(){const out=[];for(let c=1;c<=state.session.courts;c++)if(!state.session.courtState[c])out.push(c);return out}
function typeCounts(){const c={MD:0,WD:0,XD:0};state.session.rounds.forEach(r=>{if(c[r.type]!==undefined)c[r.type]++});Object.values(state.session.courtState).forEach(o=>{if(c[o.type]!==undefined)c[o.type]++});return c}
function playerStats(id){const rs=state.session.rounds.filter(r=>[...r.teamA,...r.teamB].some(p=>p.id===id));const roles={carry:0,intensity:0,light:0},tiers={A:0,B:0,C:0};rs.forEach(r=>{const role=roundRole(r,id);if(role)roles[role]++;tiers[roundTier(r)]++});return{n:rs.length,roles,tiers}}
function elapsed(ts){const m=Math.floor((Date.now()-ts)/60000);return m<1?'just started':m+' min on court'}
function toast(text,undo){const t=$('#toast');t.innerHTML=undo?`${text} · <button id="undo-toast" class="text-button">Undo</button>`:text;t.classList.add('show');if(undo)$('#undo-toast').onclick=()=>{undo();t.classList.remove('show')};clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500)}
function initials(name){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function timeAgo(ts){if(!ts)return'';const s=Math.floor((Date.now()-ts)/1000);if(s<45)return'just now';const m=Math.floor(s/60);if(m<60)return`${m}m ago`;return`${Math.floor(m/60)}h ago`}
function recKey(rec){return rec?rec.matches.map(m=>m.players.map(p=>p.playerId).sort().join(',')).sort().join('|'):null}
async function api(path,opts={}){const c=cfg();if(!c)throw Error('Not connected');const r=await fetch(c.url.replace(/\/$/,'')+path,{...opts,headers:{'content-type':'application/json','x-app-key':c.key,...opts.headers}});let body={};try{body=await r.json()}catch{}if(!r.ok)throw Error(body.error||`Request failed (${r.status})`);return body}
function cachePlayers(players){state.players=players;write(CACHE,{syncedAt:Date.now(),players})}
async function loadPlayers(){if(state.demo){cachePlayers(demoPlayers);return}const cached=read(CACHE);if(cached?.players)state.players=cached.players;const body=await api('/api/players');cachePlayers(body.players)}

function newSession(){const s=state.session;const used=s&&(s.roster.length||s.rounds.length||s.me.games.length);const unsent=s&&s.me.games.length&&!s.me.exportedAt;if(used&&!confirm(unsent?'Your game log for tonight hasn’t been sent to Obsidian yet. End this session anyway?':'End this session and clear tonight’s counters?'))return;if(s&&s.me.focusNext.length)setMeCfg({lastFocus:{items:s.me.focusNext,date:localDate(s.startedAt)}});state.session=blankSession();state.openCards=new Set();saveSession();renderLive();scrollTo(0,0);if(used)toast('New session started')}
function setCourts(next){const s=state.session;next=Math.max(0,Math.min(10,next));if(next===s.courts)return;const stranded=Object.keys(s.courtState).map(Number).filter(c=>c>next);if(stranded.length&&!confirm(`Court ${stranded.join(', ')} still has players on it. Remove the court and clear them without logging?`))return;stranded.forEach(c=>delete s.courtState[c]);s.courts=next;saveSession();renderLive();if(stranded.length)toast(`Court ${stranded.join(', ')} cleared · no counts changed`)}
async function syncPlayers(loud){if(state.syncing||(!cfg()&&!state.demo))return;state.syncing=true;renderSyncNote();try{await loadPlayers();if(loud)toast('Player list updated')}catch{if(loud)toast('Couldn’t reach Notion · using the saved list')}finally{state.syncing=false;renderSyncNote();if($('#roster-dialog').open)renderRosterPicker()}}
function renderSyncNote(){const el=$('#roster-sync');if(!el)return;const at=read(CACHE)?.syncedAt;el.textContent=state.syncing?'Syncing with Notion…':state.demo?'Demo players':at?`Synced ${timeAgo(at)}`:'Not synced yet'}
function openRosterDialog(){state.rosterPick=new Set();$('#roster-search').value='';renderRosterPicker();renderSyncNote();$('#roster-dialog').showModal();syncPlayers(false)}
function renderRosterPicker(){const q=$('#roster-search').value.trim().toLowerCase();const inSession=new Set(state.session.roster.map(p=>p.playerId));const list=state.players.filter(p=>p.name.toLowerCase().includes(q)).sort((a,b)=>(inSession.has(a.id)-inSession.has(b.id))||a.name.localeCompare(b.name));const missing=p=>[!p.gender&&'gender',!p.level&&'level'].filter(Boolean).join(' & ');$('#roster-picker').innerHTML=list.map(p=>{const inS=inSession.has(p.id),sel=state.rosterPick.has(p.id);return `<button type="button" class="picker ${sel?'selected':''} ${p.incomplete?'incomplete':''} ${inS?'in-session':''}" data-roster-pick="${esc(p.id)}" aria-pressed="${sel}" ${inS?'disabled':''}><span class="avatar">${esc(initials(p.name))}</span><span class="pick-text"><strong>${esc(p.name)}</strong><small>${inS?'Already in tonight’s session':p.incomplete?'Tap to add missing '+missing(p):`${esc(p.gender)} · Level ${esc(p.level)}`}</small></span>${sel?'<span class="pick-check" aria-hidden="true">✓</span>':''}</button>`}).join('')||`<div class="empty-state">${state.players.length?'No players match.':(cfg()||state.demo)?(state.syncing?'Loading players from Notion…':'No players loaded. Check your connection, then tap Sync.'):'The player table isn’t connected yet.<br><button type="button" class="primary" id="roster-connect">Connect player table</button>'}</div>`;$$('[data-roster-pick]').forEach(b=>b.onclick=()=>{const p=state.players.find(x=>x.id===b.dataset.rosterPick);if(!p)return;if(p.incomplete){openPlayerDialog(p);return}state.rosterPick.has(p.id)?state.rosterPick.delete(p.id):state.rosterPick.add(p.id);renderRosterPicker()});const rc=$('#roster-connect');if(rc)rc.onclick=()=>{$('#roster-dialog').close();setView('connect-view')};const addable=list.filter(p=>!inSession.has(p.id)&&!p.incomplete);const n=state.rosterPick.size;$('#roster-count').textContent=`${n} selected · ${state.session.roster.length} in session`;const all=$('#roster-all');all.hidden=!addable.length;const allOn=addable.length&&addable.every(p=>state.rosterPick.has(p.id));all.textContent=allOn?'Clear selection':(q?'Select all shown':'Select all');all.onclick=()=>{addable.forEach(p=>allOn?state.rosterPick.delete(p.id):state.rosterPick.add(p.id));renderRosterPicker()};$('#roster-confirm').disabled=!n;$('#roster-confirm').textContent=n?`Add ${n} player${n===1?'':'s'}`:'Add players'}
function addPicked(){const s=state.session;const add=[...state.rosterPick].map(id=>state.players.find(p=>p.id===id)).filter(p=>p&&!p.incomplete&&!s.roster.some(r=>r.playerId===p.id));$('#roster-dialog').close();if(!add.length)return;if(!s.roster.length&&!s.rounds.length)s.startedAt=Date.now();const start=minActiveCount(),mid=s.rounds.length>0;add.forEach(p=>s.roster.push({playerId:p.id,name:p.name,gender:p.gender,level:p.level,count:start,status:'playing',...(mid?{lastUpdated:Date.now()}:{})}));const ids=new Set(add.map(p=>p.id));saveSession();renderLive();toast(`${add.length} player${add.length===1?'':'s'} added${mid?` · starting at ${start}`:''}`,()=>{const busy=busyIds();s.roster=s.roster.filter(r=>!ids.has(r.playerId)||busy.has(r.playerId));saveSession();renderLive()})}
function saveSession(){write(SESSION,state.session)}
function minActiveCount(){const a=state.session.roster.filter(p=>p.status!=='benched');return a.length?Math.min(...a.map(p=>p.count)):0}
function summary(){const a=state.session.roster.filter(p=>p.status!=='benched'),b=state.session.roster.length-a.length,counts=a.map(p=>p.count),min=counts.length?Math.min(...counts):0,max=counts.length?Math.max(...counts):0;return[{v:a.length,l:'Active'},{v:b,l:'Benched'},{v:`${min}–${max}`,l:'Play range'},{v:max-min,l:'Fairness gap'}]}
function renderTeam(team){return `<div class="team">${team.map(p=>`<strong>${p.name}</strong>`).join('')}<small>${team.map(p=>p.level).join('')} · counts ${team.map(p=>p.count).join('/')}</small></div>`}
function avgLevel(match){const LEVEL={A:3,B:2,C:1};return match.players.reduce((s,p)=>s+LEVEL[p.level],0)/match.players.length}
function levelTier(match){const a=avgLevel(match);if(a>=2.5)return'A';if(a>=1.5)return'B';return'C'}
function renderCourtCard(m){return `<article class="court-card"><div class="court-head"><div><strong>Option ${m.court}</strong> <span class="court-type">${m.type}</span></div><button type="button" class="court-edit" data-edit-court="${m.court}" aria-label="Edit Court ${m.court} lineup">✎</button></div><div class="teams">${renderTeam(m.teamA)}<span class="versus">VS</span>${renderTeam(m.teamB)}</div><p class="why">Level gap ${m.levelGap} · selected from the lowest available counts</p><button class="played" data-start="${m.court}" ${emptyCourts().length?'':'disabled'}>${emptyCourts().length?'Put on Court '+emptyCourts()[0]:'All courts busy'}</button></article>`}
function renderCarousel(rec){const types=[{key:'XD',label:'Mixed'},{key:'MD',label:'Men'},{key:'WD',label:'Women'}];const byType={};rec.matches.forEach(m=>{(byType[m.type]=byType[m.type]||[]).push(m)});const activeTabs=types.filter(t=>byType[t.key]?.length);if(!activeTabs.length)return `<div class="empty-state"><strong>No legal court yet.</strong><br>${rec.incomplete.length?'Complete missing Gender or Level.':'The available gender mix cannot form MD, WD, or XD.'}</div>`;const tabs=activeTabs.map((t,i)=>`<button type="button" class="carousel-tab${i===0?' active':''}" data-carousel-tab="${t.key}">${t.label} <span class="tab-count">${byType[t.key].length}</span></button>`).join('');const panels=activeTabs.map((t,i)=>{const matches=byType[t.key];const grouped={A:[],B:[],C:[]};matches.forEach(m=>grouped[levelTier(m)].push(m));const sections=['A','B','C'].filter(l=>grouped[l].length).map(l=>`<div class="level-group"><p class="level-group-head">Level ${l}</p>${grouped[l].map(renderCourtCard).join('')}</div>`).join('');return `<div class="carousel-panel${i===0?' active':''}" data-panel="${t.key}">${sections}</div>`}).join('');return `<div class="carousel-tabs">${tabs}</div><div class="carousel-track">${panels}</div>`}
function bindCarousel(){$$('[data-carousel-tab]').forEach(tab=>tab.onclick=()=>{$$('.carousel-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');$$('.carousel-panel').forEach(p=>p.classList.remove('active'));const panel=$(`[data-panel="${tab.dataset.carouselTab}"]`);if(panel)panel.classList.add('active')})}
function renderOccupiedCourt(c,o){const side=t=>`<div class="team">${t.map(x=>`<strong>${nameOf(x.id)}</strong>`).join('')}<small>${t.map(x=>x.level).join('')}</small></div>`;return `<article class="court-card live-court"><div class="court-head"><div><strong>Court ${c}</strong> <span class="court-type">${o.type} · LIVE</span></div><button type="button" class="court-edit" data-recourt="${c}" aria-label="Change Court ${c} lineup">✎</button></div><div class="teams">${side(o.teamA)}<span class="versus">VS</span>${side(o.teamB)}</div><p class="why">${elapsed(o.startedAt)}</p><button class="played" data-end="${c}">End round · +1 all</button><button type="button" class="court-clear" data-clear="${c}">Clear without logging</button></article>`}
function renderEmptyCourt(c){return `<article class="court-card empty-court"><div class="court-head"><div><strong>Court ${c}</strong> <span class="court-type">FREE</span></div></div><p class="why">Nobody on this court yet.</p><button class="played" data-fill="${c}">Pick 4 players</button></article>`}
function renderCourts(){const s=state.session;if(!s.courts){$('#courts').innerHTML=`<article class="empty-state setup-card"><strong>How many courts tonight?</strong><div class="court-chips">${[1,2,3,4].map(n=>`<button type="button" class="chip-btn" data-set-courts="${n}">${n}</button>`).join('')}</div><small>Change it any time with − / + above.</small></article>`;$('#courts-note').textContent='';return}const out=[];for(let c=1;c<=s.courts;c++){const o=s.courtState[c];out.push(o?renderOccupiedCourt(c,o):renderEmptyCourt(c))}$('#courts').innerHTML=out.join('');const live=Object.keys(s.courtState).length;$('#courts-note').textContent=`${live} of ${s.courts} in play · ${s.rounds.length} round${s.rounds.length===1?'':'s'} logged`;$$('[data-fill]').forEach(b=>b.onclick=()=>openLineupDialog([],Number(b.dataset.fill)));$$('[data-recourt]').forEach(b=>b.onclick=()=>{const c=Number(b.dataset.recourt);const o=s.courtState[c];openLineupDialog([...o.teamA,...o.teamB].map(p=>p.id),c)});$$('[data-end]').forEach(b=>b.onclick=()=>endRound(Number(b.dataset.end)));$$('[data-clear]').forEach(b=>b.onclick=()=>clearCourt(Number(b.dataset.clear)))}
function startCourt(court,ids,partition){const roster=state.session.roster;const four=ids.map(id=>roster.find(x=>x.playerId===id)).filter(Boolean);if(four.length!==4)return;const[ia,ib]=PARTITIONS[partition%3];const snap=p=>({id:p.playerId,level:p.level,gender:p.gender});const prior=state.session.courtState[court];state.session.courtState[court]={teamA:ia.map(i=>snap(four[i])),teamB:ib.map(i=>snap(four[i])),type:lineupType(four),startedAt:prior?prior.startedAt:Date.now()};saveSession();renderLive();toast(`Court ${court} started`)}
function clearCourt(court){const o=state.session.courtState[court];if(!o)return;delete state.session.courtState[court];saveSession();renderLive();toast(`Court ${court} cleared · no counts changed`,()=>{state.session.courtState[court]=o;saveSession();renderLive()})}
function endRound(court){const s=state.session;const o=s.courtState[court];if(!o)return;const ids=[...o.teamA,...o.teamB].map(p=>p.id);const before=ids.map(id=>({id,count:s.roster.find(x=>x.playerId===id).count}));const round={id:crypto.randomUUID(),court,type:o.type,teamA:o.teamA,teamB:o.teamB,startedAt:o.startedAt,endedAt:Date.now()};s.rounds.push(round);delete s.courtState[court];ids.forEach(id=>{const r=s.roster.find(x=>x.playerId===id);r.count++;r.lastUpdated=Date.now()});saveSession();renderLive();const undo=()=>{s.rounds=s.rounds.filter(r=>r.id!==round.id);s.courtState[court]=o;before.forEach(x=>s.roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()};toast(`Court ${court} logged · +1 all`,undo);promptMe(round,undo,`Undo ending Court ${court}`)}
function logLooseRound(ids,partition){const s=state.session;const four=ids.map(id=>s.roster.find(x=>x.playerId===id)).filter(Boolean);if(four.length!==4)return;const[ia,ib]=PARTITIONS[partition%3];const snap=p=>({id:p.playerId,level:p.level,gender:p.gender});const round={id:crypto.randomUUID(),court:null,type:lineupType(four),teamA:ia.map(i=>snap(four[i])),teamB:ib.map(i=>snap(four[i])),startedAt:Date.now(),endedAt:Date.now()};const before=four.map(p=>({id:p.playerId,count:p.count}));s.rounds.push(round);four.forEach(p=>{p.count++;p.lastUpdated=Date.now()});saveSession();renderLive();const undo=()=>{s.rounds=s.rounds.filter(r=>r.id!==round.id);before.forEach(x=>s.roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()};toast('Round logged · +1 all',undo);promptMe(round,undo,'Undo logging this round')}
function renderLive(avoid){setView('live-view');const s=state.session;const empty=!s.roster.length;$('#live-kicker').textContent=s.rounds.length||Object.keys(s.courtState).length?'LIVE SESSION':'TONIGHT';$('#live-courts').textContent=`${s.courts} court${s.courts===1?'':'s'}`;$('#session-title').textContent=new Date(s.startedAt).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'});$('#summary').hidden=empty;$('#summary').innerHTML=empty?'':summary().map(x=>`<div class="summary-item"><strong>${x.v}</strong><span>${x.l}</span></div>`).join('');renderCourts();const free=emptyCourts();const busy=busyIds();const ready=s.roster.filter(p=>p.status!=='benched'&&!busy.has(p.playerId));let rec=null,html;if(!s.courts)html='<div class="empty-state"><strong>No courts yet.</strong><br>Pick how many courts you have, and match-ups show up here.</div>';else if(ready.length<4)html=`<div class="empty-state"><strong>${empty?'No players yet.':`${ready.length} player${ready.length===1?'':'s'} free.`}</strong><br>${empty?'Add at least 4 players to see match-ups.':busy.size?'Match-ups show up again as courts finish.':'Add at least 4 players to see match-ups.'}${busy.size&&!empty?'':'<br><button type="button" class="primary" data-open-roster>+ Add players</button>'}</div>`;else{const avail=s.roster.map(p=>busy.has(p.playerId)?{...p,status:'benched'}:p);rec=recommend(avail,Math.max(1,free.length),typeCounts(),avoid||new Set());const upNext=free.length?'':'<p class="muted" style="margin:0 0 10px">All courts busy — here’s who’s up next.</p>';html=upNext+renderCarousel(rec)}s.lastRecommendation=rec;saveSession();$('#refresh-recommendation').disabled=!rec;$('#log-custom-match').hidden=s.roster.length<4;$('#recommendations').innerHTML=html;if(rec){bindCarousel();$$('[data-start]').forEach(b=>b.onclick=()=>{const m=rec.matches.find(x=>x.court===Number(b.dataset.start));const target=emptyCourts()[0];if(!m||!target)return;b.disabled=true;startCourt(target,[...m.teamA,...m.teamB].map(p=>p.playerId),0)});$$('[data-edit-court]').forEach(b=>b.onclick=()=>{const m=rec.matches.find(x=>x.court===Number(b.dataset.editCourt));openLineupDialog(m?[...m.teamA,...m.teamB].map(p=>p.playerId):[],emptyCourts()[0]??null)})}const wait=rec?[...rec.waiting,...rec.incomplete]:[];$('#waiting').innerHTML=wait.length?`<strong>Waiting (${wait.length})</strong><br>${wait.map(p=>p.name).join(' · ')}${rec.incomplete.length?'<br><small>Incomplete players are not eligible until corrected.</small>':''}`:'';renderLedger();renderMe()}

function statsBlock(p,st){st=st||playerStats(p.playerId);if(!st.n)return '<div class="player-stats"><p class="muted" style="margin:0">No rounds logged yet — start a court to build this player\u2019s history.</p></div>';const roles=['carry','intensity','light'].map(k=>`<span class="chip chip-${k}">${ROLE_LABEL[k]} ×${st.roles[k]}</span>`).join('');const tiers=['A','B','C'].map(k=>`<span class="chip chip-lv chip-lv-${k}">${k} ×${st.tiers[k]}</span>`).join('');const drift=p.count!==st.n?`<p class="stat-note">Ledger says ${p.count}; ${st.n} round${st.n===1?'':'s'} logged (rest were manual adjustments).</p>`:'';return `<div class="player-stats"><div class="stat-line"><span class="stat-label">Role mix</span><span class="chips">${roles}</span></div><div class="stat-line"><span class="stat-label">Level mix</span><span class="chips">${tiers}</span></div>${drift}</div>`}
function playerRow(p){const oc=courtOf(p.playerId);const open=state.openCards.has(p.playerId);const benched=p.status==='benched';const st=playerStats(p.playerId);const glance=st.n?`<div class="role-glance">${['carry','intensity','light'].map(k=>`<span class="chip chip-${k} chip-mini" title="${ROLE_LABEL[k]} ×${st.roles[k]}">${ROLE_LABEL[k][0]}${st.roles[k]}</span>`).join('')}</div>`:'';return `<div class="player-block${open?' open':''}"><div class="player-row ${benched?'benched':''}${oc?' on-court':''}"><div class="player-meta"><button type="button" class="name-btn" data-card="${p.playerId}" aria-expanded="${open}">${p.name}${oc?` <span class="oncourt-badge">Court ${oc}</span>`:''}</button><small>${p.gender} · <button type="button" class="grade-btn grade-${p.level}" data-grade="${p.playerId}" aria-label="Change ${p.name} level (now ${p.level})">${p.level}</button>${p.lastUpdated?` · ${timeAgo(p.lastUpdated)}`:''}</small>${glance}</div><div class="row-actions"><div class="count-controls"><button data-count="${p.playerId}" data-delta="-1" aria-label="Subtract one game from ${p.name}">−</button><output aria-label="${p.name} has played ${p.count} games">${p.count}</output><button data-count="${p.playerId}" data-delta="1" aria-label="Add one game to ${p.name}">+</button></div><button type="button" class="bench-icon${benched?' is-benched':''}" data-bench="${p.playerId}" aria-label="${benched?'Return':'Bench'} ${p.name}" title="${benched?'Return to play':'Bench (sit out)'}">${benched?'▶':'⏸'}</button></div></div>${open?statsBlock(p,st):''}</div>`}
function cycleGrade(id){const grades=['A','B','C'];const p=state.session.roster.find(x=>x.playerId===id);if(!p)return;const oldLevel=p.level;const next=grades[(grades.indexOf(p.level)+1)%3];p.level=next;p.lastUpdated=Date.now();const cached=state.players.find(x=>x.id===id);if(cached)cached.level=next;cachePlayers(state.players);saveSession();renderLive();toast(`${p.name} → Level ${next}`);if(!state.demo){api(`/api/players/${id}`,{method:'PATCH',body:JSON.stringify({level:next})}).catch(()=>toast(`${p.name} level saved locally · Notion sync failed`))}}
function renderLedger(){$('#ledger-search').hidden=!state.session.roster.length;if(!state.session.roster.length){$('#ledger').innerHTML='<div class="empty-state"><strong>Nobody here yet.</strong><br>Add who’s at the hall tonight — you can keep adding as people arrive.<br><button type="button" class="primary" data-open-roster>+ Add players</button></div>';return}const q=$('#ledger-search').value.trim().toLowerCase();const rows=[...state.session.roster].filter(p=>p.name.toLowerCase().includes(q)).sort((a,b)=>a.count-b.count||a.name.localeCompare(b.name));const playing=rows.filter(p=>p.status!=='benched'),benched=rows.filter(p=>p.status==='benched');$('#ledger').innerHTML=(playing.length?`<div class="ledger-group"><p class="ledger-group-head">Playing (${playing.length})</p>${playing.map(playerRow).join('')}</div>`:(q?'<p class="muted">No players match.</p>':''))+(benched.length?`<details class="ledger-group"${playing.length?'':' open'}><summary class="ledger-group-head">Benched (${benched.length})</summary>${benched.map(playerRow).join('')}</details>`:'');$$('[data-count]').forEach(b=>b.onclick=()=>adjustCount(b.dataset.count,Number(b.dataset.delta)));$$('[data-bench]').forEach(b=>b.onclick=()=>toggleBench(b.dataset.bench));$$('[data-grade]').forEach(b=>b.onclick=()=>cycleGrade(b.dataset.grade));$$('[data-card]').forEach(b=>b.onclick=()=>{const id=b.dataset.card;state.openCards.has(id)?state.openCards.delete(id):state.openCards.add(id);renderLedger()})}
function adjustCount(id,d){const p=state.session.roster.find(x=>x.playerId===id);p.count=Math.max(0,p.count+d);p.lastUpdated=Date.now();saveSession();renderLive()}
function toggleBench(id){const p=state.session.roster.find(x=>x.playerId===id);p.status=p.status==='benched'?'playing':'benched';saveSession();renderLive()}
function playedIds(ids){const roster=state.session.roster;const before=ids.map(id=>({id,count:roster.find(x=>x.playerId===id).count}));ids.forEach(id=>{const r=roster.find(x=>x.playerId===id);r.count++;r.lastUpdated=Date.now()});saveSession();renderLive();toast('Four counts updated',()=>{before.forEach(x=>roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()})}
function played(match,button){if(!match||button.disabled)return;button.disabled=true;playedIds(match.players.map(p=>p.playerId))}

function openLineupDialog(prefillIds,court){state.lineupSelected=new Set(prefillIds);state.lineupCourt=court??null;state.lineupPartition=0;$('#lineup-dialog-title').textContent=court?`Court ${court} lineup`:'Log a round';$('#lineup-search').value='';$('#lineup-error').textContent='';renderLineupPicker();$('#lineup-dialog').showModal()}
function renderLineupPicker(){const q=$('#lineup-search').value.trim().toLowerCase();const busy=busyIds();const eligible=state.session.roster.filter(p=>p.status!=='benched'&&p.name.toLowerCase().includes(q)&&(!busy.has(p.playerId)||state.lineupSelected.has(p.playerId)||courtOf(p.playerId)===state.lineupCourt)).sort((a,b)=>{const ab=busy.has(a.playerId)?1:0,bb=busy.has(b.playerId)?1:0;return ab-bb||a.count-b.count||(a.lastUpdated??0)-(b.lastUpdated??0)||a.name.localeCompare(b.name)});$('#lineup-picker').innerHTML=eligible.map(p=>`<button type="button" class="picker ${state.lineupSelected.has(p.playerId)?'selected':''}" data-lineup-pick="${p.playerId}" aria-pressed="${state.lineupSelected.has(p.playerId)}"><span class="avatar">${initials(p.name)}</span><span><strong>${p.name}</strong><small>${p.gender||'Gender missing'} · ${p.level?`Level ${p.level}`:'Level missing'} · ${p.count} played</small></span></button>`).join('')||'<p class="muted">No players available.</p>';$$('[data-lineup-pick]').forEach(b=>b.onclick=()=>{const id=b.dataset.lineupPick;if(state.lineupSelected.has(id))state.lineupSelected.delete(id);else{if(state.lineupSelected.size>=4){toast('Only 4 players can play a court');return}state.lineupSelected.add(id)}renderLineupPicker()});$('#lineup-count').textContent=`${state.lineupSelected.size} of 4 selected`;renderLineupTeams();const ready=state.lineupSelected.size===4;$('#lineup-confirm').disabled=!ready;$('#lineup-confirm').textContent=state.lineupCourt?`Start on Court ${state.lineupCourt}`:'Log round · +1 all'}
function renderLineupTeams(){const box=$('#lineup-teams');if(state.lineupSelected.size!==4){box.hidden=true;box.innerHTML='';return}box.hidden=false;const four=[...state.lineupSelected].map(id=>state.session.roster.find(p=>p.playerId===id));const[ia,ib]=PARTITIONS[state.lineupPartition%3];const type=lineupType(four);const side=idx=>`<div class="lineup-side">${idx.map(i=>`<strong>${four[i].name}</strong>`).join('')}<small>${idx.map(i=>four[i].level).join('')}</small></div>`;box.innerHTML=`<div class="lineup-teams-head"><span class="court-type">${type}</span><button type="button" id="swap-teams" class="text-button">⇄ Swap pairing</button></div><div class="lineup-teams-row">${side(ia)}<span class="versus">VS</span>${side(ib)}</div>${type==='MIX'?'<p class="stat-note">Uneven gender mix — allowed, but not MD, WD, or XD.</p>':''}`;$('#swap-teams').onclick=()=>{state.lineupPartition=(state.lineupPartition+1)%3;renderLineupTeams()}}


function openPlayerDialog(player=null){$('#player-dialog-title').textContent=player?'Edit player':'Add player';$('#edit-player-id').value=player?.id||'';$('#player-name').value=player?.name||'';$('#player-gender').value=player?.gender||'';$('#player-level').value=player?.level||'';$('#player-error').textContent='';$('#player-dialog').showModal()}
async function savePlayer(e){e.preventDefault();const id=$('#edit-player-id').value;const input={name:$('#player-name').value.trim(),gender:$('#player-gender').value,level:$('#player-level').value};if(!input.name||!input.gender||!input.level){$('#player-error').textContent='Name, Gender, and Level are required.';return}const dup=state.players.find(p=>p.id!==id&&p.name.trim().toLowerCase()===input.name.toLowerCase());if(dup&&!confirm(`${dup.name} already exists. Create another player with this name?`))return;$('#save-player').disabled=true;try{let saved;if(state.demo){saved={id:id||crypto.randomUUID(),...input,active:true,incomplete:false}}else saved=await api(id?`/api/players/${id}`:'/api/players',{method:id?'PATCH':'POST',body:JSON.stringify(input)});const i=state.players.findIndex(p=>p.id===saved.id);if(i>=0)state.players[i]=saved;else state.players.push(saved);cachePlayers(state.players);if(state.session){const existing=state.session.roster.find(p=>p.playerId===saved.id);if(existing){Object.assign(existing,{name:saved.name,gender:saved.gender,level:saved.level})}else state.session.roster.push({playerId:saved.id,name:saved.name,gender:saved.gender,level:saved.level,count:minActiveCount(),status:'playing',lastUpdated:Date.now()});saveSession();renderLive()}if($('#roster-dialog').open)renderRosterPicker();$('#player-dialog').close();toast(id?'Player updated':'Player added')}catch(err){$('#player-error').textContent=err.message}finally{$('#save-player').disabled=false}}
async function boot(){state.demo=read(DEMO)===true;const s=read(SESSION);if(validSession(s))state.session=migrateSession(s);const cached=read(CACHE);if(cached?.players)state.players=cached.players;if(!cfg()&&!state.demo&&!state.session){setView('connect-view');return}ensureSession();renderLive();syncPlayers(false)}

$('#connect').onclick=async()=>{const url=$('#worker-url').value.trim(),key=$('#app-key').value.trim();if(!url||!key)return;write(CFG,{url,key});try{state.demo=false;localStorage.removeItem(DEMO);await loadPlayers();ensureSession();renderLive()}catch(e){localStorage.removeItem(CFG);$('#connect-error').textContent=e.message}};
$('#demo').onclick=async()=>{state.demo=true;write(DEMO,true);await loadPlayers();ensureSession();renderLive()};
$('#ledger-search').oninput=renderLedger;$('#roster-search').oninput=renderRosterPicker;$('#roster-confirm').onclick=addPicked;$('#roster-new').onclick=()=>openPlayerDialog();$('#roster-sync-btn').onclick=()=>syncPlayers(true);$$('[data-live-court-delta]').forEach(b=>b.onclick=()=>setCourts(state.session.courts+Number(b.dataset.liveCourtDelta)));
document.addEventListener('click',e=>{const t=e.target.closest('[data-open-roster],[data-set-courts]');if(!t||!state.session)return;if(t.dataset.setCourts)setCourts(Number(t.dataset.setCourts));else openRosterDialog()});
$('#new-session').onclick=newSession;$('#refresh-recommendation').onclick=()=>{const prev=state.session.lastRecommendation;const before=recKey(prev);const avoid=new Set((prev?.matches||[]).flatMap(m=>[m.players.map(p=>p.playerId).sort().join('|')]));renderLive(avoid);const after=recKey(state.session.lastRecommendation);toast(before===after?'Refreshed · that\'s the fairest option available right now':'Refreshed · new match-up')};$('#log-custom-match').onclick=()=>openLineupDialog([],null);$('#lineup-search').oninput=renderLineupPicker;$('#lineup-confirm').onclick=()=>{if(state.lineupSelected.size!==4){$('#lineup-error').textContent='Pick exactly 4 players.';return}const ids=[...state.lineupSelected],part=state.lineupPartition,court=state.lineupCourt;$('#lineup-dialog').close();if(court)startCourt(court,ids,part);else logLooseRound(ids,part)};$('#player-form').addEventListener('submit',savePlayer);$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
setInterval(()=>{if(state.session&&!$('#live-view').hidden){renderCourts();renderLedger()}},30000);
/* ── My game: coach-grade between-games self-scout, exported per session to Obsidian (mylog.js) ── */
const DEF_FOLDER='Badminton/Netflick';
const GAME_SPEC=[
 {h:'Outcome'},
 {k:'result',l:'Result',req:1,o:[['won','Won'],['lost','Lost']]},
 {k:'margin',l:'Score',o:[['close','Close'],['clear','Clear']]},
 {h:'Errors'},
 {k:'errors',l:'Unforced errors',req:1,o:[['low','Few'],['high','Many']]},
 {k:'errorSources',l:'Mostly from · up to 2',multi:2,o:ERROR_SOURCES.map(x=>[x.key,x.label])},
 {k:'errorCause',l:'Mostly because',o:CAUSES.map(x=>[x.key,x.label])},
 {h:'Serve'},
 {c:'serveFaults',l:'Serve faults / into the net'},{c:'flickTried',l:'Flick serves tried'},{c:'flickLanded',l:'…that landed well'},
 {h:'Receive'},
 {k:'returnQ',l:'My returns of serve',o:[['attack','Took the attack'],['neutral','Neutral'],['gave','Gave it away']]},
 {c:'flickUnreached',l:'Flick serves I couldn’t reach'},
 {h:'Rally & partner'},
 {k:'control',l:'Who had the attack',o:[['us','Us'],['even','Even'],['them','Them']]},
 {k:'rotation',l:'Positional mix-ups',o:[['clean','None'],['some','Some'],['many','Many']]},
 {h:'Body'},
 {k:'legs',l:'Legs',o:[['fresh','Fresh'],['ok','OK'],['heavy','Heavy']]}
];
function chipset(key,opts,sel,attr='data-pick'){return `<div class="chipset">${opts.map(([v,l])=>{const on=Array.isArray(sel)?sel.includes(v):sel===v;return `<button type="button" ${attr}="${key}" data-v="${esc(v)}" aria-pressed="${on}">${esc(l)}</button>`}).join('')}</div>`}
function meMd(){const s=state.session;return toMarkdown({startedAt:s.startedAt,me:s.me,rounds:s.rounds,meId:meCfg().playerId,nameOf})}
function meTouched(){state.session.me.exportedAt=null;saveSession();renderMe()}
function gameLine(g){const s=state.session;const sd=sides(s.rounds.find(r=>r.id===g.roundId),meCfg().playerId,nameOf);const vs=sd?`w/ ${sd.partner.join(', ')} vs ${sd.opponents.join(' & ')}`:'Game';const res=g.result?(g.result==='won'?'W':'L')+(g.margin?` ${g.margin}`:''):'';const err=g.errors==='high'?`errors MANY${(g.errorSources||[]).length?` (${g.errorSources.map(sourceLabel).join(', ').toLowerCase()})`:''}`:g.errors==='low'?'errors few':'';const ret=g.returnQ==='gave'?'returns gave away':g.returnQ==='attack'?'returns attacked':'';return `${res?`<b>${res}</b> · `:''}${esc(vs)}<small>${[localTime(g.at),g.role?g.role:'',err,ret,g.flickTried?`flick ${g.flickLanded}/${g.flickTried}`:'',g.flickUnreached?`${g.flickUnreached} flick missed`:''].filter(Boolean).join(' · ')}</small>`}
function renderMe(){const box=$('#me-panel');if(!box||!state.session)return;const s=state.session,m=s.me,c=meCfg(),sum=summarize(m.games),sug=suggestFocus(m.games),sugMap=Object.fromEntries(sug.map(x=>[x.key,x.reason]));
const focusIn=m.focusIn.length?`<div class="me-focus-in"><p class="kicker">Tonight’s focus${c.lastFocus?.date?` · set ${esc(c.lastFocus.date)}`:''}</p>${m.focusIn.map(i=>`<div class="me-hit"><span>${esc(focusLabel(i))}</span>${chipset(i,[['yes','Hit it'],['partly','Partly'],['no','No']],m.focusHit[i]||null,'data-hit')}</div>`).join('')}<p class="stat-note">Mark at the end of the night: did you actually work on it?</p></div>`:'';
const opts=s.roster.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${esc(p.playerId)}"${p.playerId===c.playerId?' selected':''}>${esc(p.name)}</option>`).join('');
const whoami=`<label class="me-who">I’m playing as<select id="me-player"><option value="">Not set — no auto-ask</option>${opts}${c.playerId&&!s.roster.some(p=>p.playerId===c.playerId)?`<option value="${esc(c.playerId)}" selected>(not in tonight’s roster)</option>`:''}</select></label><p class="stat-note">When one of your rounds ends, the quick log opens by itself.</p>`;
const energy=`<div class="me-q"><p class="field-label">Energy coming in</p>${chipset('energy',[['low','Low'],['ok','OK'],['high','High']],m.energy,'data-sess')}</div>`;
const stats=sum.n?`<div class="summary me-summary">${[{v:`${sum.won}–${sum.lost}`,l:`W–L · ${sum.n} game${sum.n===1?'':'s'}`},{v:`${sum.errorHeavy}/${sum.n}`,l:'Error-heavy'},{v:sum.sources[0]?sourceLabel(sum.sources[0][0]):'—',l:'Top leak'},{v:sum.tried?`${sum.landed}/${sum.tried}`:'—',l:'Flick serve'}].map(x=>`<div class="summary-item"><strong>${esc(x.v)}</strong><span>${x.l}</span></div>`).join('')}</div>`:'';
const games=m.games.length?`<div class="me-games">${m.games.map((g,i)=>`<button type="button" class="me-game" data-me-edit="${g.id}"><span class="n">G${i+1}</span><span>${gameLine(g)}</span></button>`).join('')}</div>`:'<div class="empty-state">No games logged yet.<br><small>Log each game between matches. Taps, not counting.</small></div>';
const endOfNight=`<div class="me-block"><p class="kicker">End of the night</p><div class="me-q"><p class="field-label">How hard was tonight overall?</p>${chipset('intensity',INTENSITY.map(x=>[x.key,x.label]),m.intensity,'data-sess')}</div><label>What worked<input id="me-worked" maxlength="160" value="${esc(m.worked)}" placeholder="One line: the thing to keep doing"></label></div>`;
const known=FOCUS.map(f=>f.key),customs=m.focusNext.filter(k=>!known.includes(k));
const order=[...sug.map(x=>x.key),...m.focusNext.filter(k=>known.includes(k)&&!sugMap[k])];
const focusOpts=order.map(k=>{const on=m.focusNext.includes(k);return `<button type="button" class="focus-opt" data-focus="${k}" aria-pressed="${on}"><span class="tick">${on?'✓':''}</span><span>${esc(focusLabel(k))}${sugMap[k]?`<small class="why-tag">${esc(sugMap[k])}</small>`:''}</span></button>`}).join('')+customs.map(k=>`<button type="button" class="focus-opt" data-focus-remove="${esc(k)}" aria-pressed="true"><span class="tick">✓</span><span>${esc(k)} <span class="sugg-tag">Tap to remove</span></span></button>`).join('');
const others=FOCUS.filter(f=>!order.includes(f.key)).map(f=>`<option value="${f.key}">${esc(f.label)}</option>`).join('');
const sent=m.exportedAt?`Sent to Obsidian ${timeAgo(m.exportedAt)}`:(m.games.length?'Not sent yet':'');
box.innerHTML=`${whoami}${energy}${focusIn}${stats}<button type="button" class="primary" id="me-log">+ Log a game</button>${games}${endOfNight}
<div class="me-block"><p class="kicker">Focus next session · pick up to ${MAX_FOCUS}</p>${sug.length?'':`<p class="stat-note">${m.games.length<2?'Suggestions appear once a pattern shows (2+ games).':'No clear pattern yet. Pick from the list.'}</p>`}<div class="me-focus">${focusOpts}</div><select id="me-focus-more" aria-label="Add a focus from the catalogue"><option value="">+ Add from the list…</option>${others}</select><div class="me-row"><input id="me-focus-custom" maxlength="80" placeholder="Or your own, e.g. backhand clear drill" aria-label="Custom focus"><button type="button" class="secondary" id="me-focus-add">Add</button></div></div>
<div class="me-block"><p class="kicker">Obsidian</p><div class="actions me-export"><button type="button" class="secondary" id="me-copy">Copy Markdown</button><button type="button" class="primary" id="me-export">Open in Obsidian</button></div><p class="stat-note">${esc(sent)}${sent?' · ':''}Note: ${esc([c.folder??DEF_FOLDER,noteName(s.startedAt)].filter(Boolean).join('/'))}.md</p>
<details class="me-settings"><summary class="ledger-group-head">Obsidian settings</summary><label>Folder in vault<input id="me-folder" value="${esc(c.folder??DEF_FOLDER)}" placeholder="${DEF_FOLDER}"></label><label>Vault name<input id="me-vault" value="${esc(c.vault||'')}" placeholder="Blank = the vault you last opened"></label></details></div>`;
$('#me-note').textContent=sum.n?`${sum.n} game${sum.n===1?'':'s'} logged`:'';
$('#me-player').onchange=e=>{setMeCfg({playerId:e.target.value||null});renderMe()};
$('#me-log').onclick=()=>openMeDialog(null,latestMyRound());
$$('[data-me-edit]').forEach(b=>b.onclick=()=>openMeDialog(m.games.find(g=>g.id===b.dataset.meEdit)));
$$('[data-sess]').forEach(b=>b.onclick=()=>{const k=b.dataset.sess,v=b.dataset.v;m[k]=m[k]===v?null:v;meTouched()});
$$('[data-hit]').forEach(b=>b.onclick=()=>{const k=b.dataset.hit,v=b.dataset.v;m.focusHit[k]=m.focusHit[k]===v?null:v;meTouched()});
$('#me-worked').onchange=e=>{m.worked=e.target.value.trim();meTouched()};
const addFocus=k=>{if(m.focusNext.includes(k))return;if(m.focusNext.length>=MAX_FOCUS){toast(`Up to ${MAX_FOCUS} — fewer is better`);return}m.focusNext.push(k);meTouched()};
$$('[data-focus]').forEach(b=>b.onclick=()=>{const k=b.dataset.focus;if(m.focusNext.includes(k)){m.focusNext=m.focusNext.filter(x=>x!==k);meTouched()}else addFocus(k)});
$$('[data-focus-remove]').forEach(b=>b.onclick=()=>{m.focusNext=m.focusNext.filter(x=>x!==b.dataset.focusRemove);meTouched()});
$('#me-focus-more').onchange=e=>{if(e.target.value)addFocus(e.target.value)};
$('#me-focus-add').onclick=()=>{const v=$('#me-focus-custom').value.trim();if(v)addFocus(v)};
$('#me-folder').onchange=e=>{setMeCfg({folder:e.target.value.trim()});renderMe()};$('#me-vault').onchange=e=>{setMeCfg({vault:e.target.value.trim()});renderMe()};
$('#me-copy').onclick=async()=>{const md=meMd();try{await navigator.clipboard.writeText(md);toast('Markdown copied')}catch{if(navigator.share)navigator.share({title:noteName(s.startedAt),text:md}).catch(()=>{});else toast('Couldn’t copy on this device')}};
$('#me-export').onclick=()=>{if(!m.games.length&&!confirm('No games logged yet. Send the note anyway?'))return;const c2=meCfg();const url=obsidianUrl({vault:c2.vault,folder:c2.folder??DEF_FOLDER,name:noteName(s.startedAt),content:meMd()});m.exportedAt=Date.now();saveSession();renderMe();location.href=url}}
function latestMyRound(){const me=meCfg().playerId,s=state.session;if(!me)return null;const r=[...s.rounds].reverse().find(r=>[...r.teamA,...r.teamB].some(p=>p.id===me));return r&&!s.me.games.some(g=>g.roundId===r.id)?r.id:null}
function promptMe(round,undo,undoLabel){const me=meCfg().playerId;if(!me||![...round.teamA,...round.teamB].some(p=>p.id===me))return;if(state.session.me.games.some(g=>g.roundId===round.id))return;setTimeout(()=>{if(!document.querySelector('dialog[open]'))openMeDialog(null,round.id,undo,undoLabel)},400)}
function openMeDialog(game,roundId=null,undo=null,undoLabel=''){const m=state.session.me;const me=meCfg().playerId;const round=state.session.rounds.find(r=>r.id===(game?game.roundId:roundId));state.meDraft=game?blankGame({...game,errorSources:[...(game.errorSources||[])]}):blankGame({roundId,role:round&&me?roundRole(round,me)||null:null});state.meUndo=undo;const d=state.meDraft;const idx=game?m.games.findIndex(g=>g.id===game.id):m.games.length;$('#me-dialog-title').textContent=`Game ${idx+1}`;const sd=sides(round,me,nameOf);$('#me-dialog-sub').textContent=sd?`With ${sd.partner.join(', ')} vs ${sd.opponents.join(' & ')}${d.role?` · ${ROLE_LABEL[d.role]} game`:''}`:'Not tied to a logged round';$('#me-note-input').value=d.note||'';$('#me-error').textContent='';$('#me-delete').hidden=!game;$('#me-undo-round').hidden=!undo;$('#me-undo-round').textContent=undoLabel||'Undo';renderMeDraft();$('#me-dialog').showModal();$('#me-form').scrollTop=0}
function renderMeDraft(){const d=state.meDraft;$('#me-fields').innerHTML=GAME_SPEC.map(f=>f.h?`<p class="me-h">${f.h}</p>`:f.c?`<div class="me-counter"><span>${f.l}</span><div class="count-controls"><button type="button" data-me-k="${f.c}" data-d="-1" aria-label="Less">−</button><output>${d[f.c]}</output><button type="button" data-me-k="${f.c}" data-d="1" aria-label="More">+</button></div></div>`:`<div class="me-q"><p class="field-label">${f.l}${f.req?' *':''}</p>${chipset(f.k,f.o,d[f.k])}</div>`).join('');
$$('#me-fields [data-pick]').forEach(b=>b.onclick=()=>{const k=b.dataset.pick,v=b.dataset.v,spec=GAME_SPEC.find(x=>x.k===k);if(spec.multi){const a=d[k];if(a.includes(v))d[k]=a.filter(x=>x!==v);else{if(a.length>=spec.multi)a.shift();a.push(v)}}else d[k]=d[k]===v?null:v;$('#me-error').textContent='';const y=$('#me-form').scrollTop;renderMeDraft();$('#me-form').scrollTop=y});
$$('#me-fields [data-me-k]').forEach(b=>b.onclick=()=>{const k=b.dataset.meK;d[k]=Math.max(0,d[k]+Number(b.dataset.d));if(k==='flickLanded'&&d.flickLanded>d.flickTried)d.flickTried=d.flickLanded;if(k==='flickTried'&&d.flickLanded>d.flickTried)d.flickLanded=d.flickTried;const y=$('#me-form').scrollTop;renderMeDraft();$('#me-form').scrollTop=y})}
function saveMeDraft(){const d=state.meDraft,m=state.session.me;const miss=GAME_SPEC.filter(f=>f.req&&!d[f.k]).map(f=>f.l.toLowerCase());if(miss.length){$('#me-error').textContent=`Tap ${miss.join(' and ')} — the rest is optional.`;return}d.note=$('#me-note-input').value.trim();if(d.id){const i=m.games.findIndex(g=>g.id===d.id);if(i>=0)m.games[i]=d}else{d.id=crypto.randomUUID();m.games.push(d)}$('#me-dialog').close();meTouched();toast(`Game ${m.games.findIndex(g=>g.id===d.id)+1} saved to my log`)}
function deleteMeGame(){const d=state.meDraft,m=state.session.me;const i=m.games.findIndex(g=>g.id===d.id);if(i<0)return;const [gone]=m.games.splice(i,1);$('#me-dialog').close();meTouched();toast('Game removed from my log',()=>{m.games.splice(i,0,gone);meTouched()})}
$('#me-save').onclick=saveMeDraft;$('#me-delete').onclick=deleteMeGame;$('#me-undo-round').onclick=()=>{$('#me-dialog').close();if(state.meUndo)state.meUndo();state.meUndo=null;toast('Round undone')};
/* Floating bottom bar (nav-kit): jump to a block of the live page, and keep
   the active item in step with whatever block the reader has scrolled to. */
const NAV_SECS=['courts','next','players','me'];
$$('#live-nav [data-gn]').forEach(b=>b.onclick=()=>{$('#sec-'+b.dataset.gn).scrollIntoView({block:'start'});window.NavKit&&NavKit.setActive(b.dataset.gn)});
addEventListener('scroll',()=>{if($('#live-view').hidden||!window.NavKit)return;const line=innerHeight*.35;let cur=NAV_SECS[0];if(innerHeight+scrollY>=document.documentElement.scrollHeight-4)cur=NAV_SECS[NAV_SECS.length-1];else for(const id of NAV_SECS){const el=$('#sec-'+id);if(el&&el.getBoundingClientRect().top<=line)cur=id}NavKit.setActive(cur)},{passive:true});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
boot();