import { recommend, PARTITIONS, strength, lineupType, roundRole, roundTier } from './engine.js';

const CFG='netflick-config-v1', CACHE='netflick-players-v1', SESSION='netflick-session-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={players:[],selected:new Set(),setupCourts:2,session:null,lastUndo:null,demo:false,lineupSelected:new Set(),lineupCourt:null,lineupPartition:0,openCards:new Set()};
const demoPlayers=[
  ['leo','Leo','Male','A'],['verry','Verry','Male','A'],['andi','Andi G','Male','B'],['charles','Charles','Male','B'],['edric','Edric','Male','C'],['richo','Richo','Male','C'],['levina','Levina','Female','A'],['lysa','Lysa','Female','A'],['tesa','Tesa','Female','B'],['vita','Vita','Female','B'],['gaby','Gaby','Female','C'],['ririn','Ririn','Female','C']
].map(([id,name,gender,level])=>({id,name,gender,level,active:true,incomplete:false}));

function read(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function cfg(){return read(CFG)}
function setView(id){['connect-view','setup-view','live-view'].forEach(x=>$('#'+x).hidden=x!==id);$('#new-session').hidden=id!=='live-view'}
function validSession(s){return s&&(s.version===1||s.version===2)&&Number.isInteger(s.courts)&&Array.isArray(s.roster)}
function migrateSession(s){if(s.version===1){s.version=2;s.rounds=[];s.courtState={}}s.rounds=s.rounds||[];s.courtState=s.courtState||{};return s}
const ROLE_LABEL={carry:'Carry',intensity:'Intensity',light:'Light'};
function nameOf(id){const r=state.session.roster.find(p=>p.playerId===id);return r?r.name:'Unknown'}
function busyIds(){return new Set(Object.values(state.session.courtState).flatMap(o=>[...o.teamA,...o.teamB].map(p=>p.id)))}
function courtOf(id){for(const[c,o]of Object.entries(state.session.courtState))if([...o.teamA,...o.teamB].some(p=>p.id===id))return Number(c);return null}
function emptyCourts(){const out=[];for(let c=1;c<=state.session.courts;c++)if(!state.session.courtState[c])out.push(c);return out}
function typeCounts(){const c={MD:0,WD:0,XD:0};state.session.rounds.forEach(r=>{if(c[r.type]!==undefined)c[r.type]++});Object.values(state.session.courtState).forEach(o=>{if(c[o.type]!==undefined)c[o.type]++});return c}
function playerStats(id){const rs=state.session.rounds.filter(r=>[...r.teamA,...r.teamB].some(p=>p.id===id));const roles={carry:0,intensity:0,light:0},tiers={A:0,B:0,C:0};rs.forEach(r=>{const role=roundRole(r,id);if(role)roles[role]++;tiers[roundTier(r)]++});return{n:rs.length,roles,tiers}}
function elapsed(ts){const m=Math.floor((Date.now()-ts)/60000);return m<1?'just started':m+' min on court'}
function toast(text,undo){const t=$('#toast');t.innerHTML=undo?`${text} · <button id="undo-toast" class="text-button">Undo</button>`:text;t.classList.add('show');if(undo)$('#undo-toast').onclick=()=>{undo();t.classList.remove('show')};clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500)}
function initials(name){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function timeAgo(ts){if(!ts)return'';const s=Math.floor((Date.now()-ts)/1000);if(s<45)return'just now';const m=Math.floor(s/60);if(m<60)return`${m}m ago`;return`${Math.floor(m/60)}h ago`}
function recKey(rec){return rec?rec.matches.map(m=>m.players.map(p=>p.playerId).sort().join(',')).sort().join('|'):null}
async function api(path,opts={}){const c=cfg();if(!c)throw Error('Not connected');const r=await fetch(c.url.replace(/\/$/,'')+path,{...opts,headers:{'content-type':'application/json','x-app-key':c.key,...opts.headers}});let body={};try{body=await r.json()}catch{}if(!r.ok)throw Error(body.error||`Request failed (${r.status})`);return body}
function cachePlayers(players){state.players=players;write(CACHE,{syncedAt:Date.now(),players})}
async function loadPlayers(){if(state.demo){cachePlayers(demoPlayers);return}const cached=read(CACHE);if(cached?.players)state.players=cached.players;const body=await api('/api/players');cachePlayers(body.players)}

function renderPicker(){const q=$('#player-search').value.trim().toLowerCase();const list=state.players.filter(p=>p.name.toLowerCase().includes(q));$('#player-picker').innerHTML=list.map(p=>`<button class="picker ${state.selected.has(p.id)?'selected':''} ${p.incomplete?'incomplete':''}" data-pick="${p.id}" aria-pressed="${state.selected.has(p.id)}"><span class="avatar">${initials(p.name)}</span><span><strong>${p.name}</strong><small>${p.gender||'Gender missing'} · ${p.level?`Level ${p.level}`:'Level missing'}</small></span></button>`).join('')||'<p class="muted">No players found.</p>';$$('[data-pick]').forEach(b=>b.onclick=()=>{const p=state.players.find(x=>x.id===b.dataset.pick);if(p.incomplete){openPlayerDialog(p);return}state.selected.has(p.id)?state.selected.delete(p.id):state.selected.add(p.id);renderPicker();renderSetupMeta()})}
function renderSetupMeta(){const selected=[...state.selected].map(id=>state.players.find(p=>p.id===id)).filter(Boolean);$('#setup-courts').textContent=state.setupCourts;$('#selected-count').textContent=`${selected.length} selected`;$('#capacity-note').textContent=`${state.setupCourts*4} playing spots · ${selected.length} players selected`;const eligible=selected.filter(p=>!p.incomplete);const warnings=[];if(eligible.length<4)warnings.push('Select at least 4 complete players.');if(eligible.length<state.setupCourts*4)warnings.push(`Only ${Math.floor(eligible.length/4)} court(s) can be filled by headcount.`);$('#setup-warning').textContent=warnings.join(' ');$('#start-session').disabled=eligible.length<4;renderPicker()}
function showSetup(){setView('setup-view');renderSetupMeta()}

function newSession(){if(state.session&&!confirm('End this session and clear tonight’s counters?'))return;localStorage.removeItem(SESSION);state.session=null;state.selected=new Set();showSetup()}
function startSession(){const roster=[...state.selected].map(id=>state.players.find(p=>p.id===id)).filter(p=>p&&!p.incomplete).map(p=>({playerId:p.id,name:p.name,gender:p.gender,level:p.level,count:0,status:'playing'}));state.session={version:2,sessionId:crypto.randomUUID(),startedAt:new Date().toISOString(),courts:state.setupCourts,roster,rounds:[],courtState:{},lastRecommendation:null};saveSession();renderLive()}
function saveSession(){write(SESSION,state.session)}
function minActiveCount(){const a=state.session.roster.filter(p=>p.status!=='benched');return a.length?Math.min(...a.map(p=>p.count)):0}
function summary(){const a=state.session.roster.filter(p=>p.status!=='benched'),b=state.session.roster.length-a.length,counts=a.map(p=>p.count),min=counts.length?Math.min(...counts):0,max=counts.length?Math.max(...counts):0;return[{v:a.length,l:'Active'},{v:b,l:'Benched'},{v:`${min}–${max}`,l:'Play range'},{v:max-min,l:'Fairness gap'}]}
function renderTeam(team){return `<div class="team">${team.map(p=>`<strong>${p.name}</strong>`).join('')}<small>${team.map(p=>p.level).join('')} · counts ${team.map(p=>p.count).join('/')}</small></div>`}
function avgLevel(match){const LEVEL={A:3,B:2,C:1};return match.players.reduce((s,p)=>s+LEVEL[p.level],0)/match.players.length}
function levelTier(match){const a=avgLevel(match);if(a>=2.5)return'A';if(a>=1.5)return'B';return'C'}
function renderCourtCard(m){return `<article class="court-card"><div class="court-head"><div><strong>Option ${m.court}</strong> <span class="court-type">${m.type}</span></div><button type="button" class="court-edit" data-edit-court="${m.court}" aria-label="Edit Court ${m.court} lineup">✎</button></div><div class="teams">${renderTeam(m.teamA)}<span class="versus">VS</span>${renderTeam(m.teamB)}</div><p class="why">Level gap ${m.levelGap} · selected from the lowest available counts</p><button class="played" data-start="${m.court}" ${emptyCourts().length?'':'disabled'}>${emptyCourts().length?'Put on Court '+emptyCourts()[0]:'All courts busy'}</button></article>`}
function renderCarousel(rec){const types=[{key:'XD',label:'Mixed'},{key:'MD',label:'Men'},{key:'WD',label:'Women'}];const byType={};rec.matches.forEach(m=>{(byType[m.type]=byType[m.type]||[]).push(m)});const activeTabs=types.filter(t=>byType[t.key]?.length);if(!activeTabs.length)return `<div class="empty-state"><strong>No legal court yet.</strong><br>${rec.incomplete.length?'Complete missing Gender or Level.':'The available gender mix cannot form MD, WD, or XD.'}</div>`;const tabs=activeTabs.map((t,i)=>`<button type="button" class="carousel-tab${i===0?' active':''}" data-carousel-tab="${t.key}">${t.label} <span class="tab-count">${byType[t.key].length}</span></button>`).join('');const panels=activeTabs.map((t,i)=>{const matches=byType[t.key];const grouped={A:[],B:[],C:[]};matches.forEach(m=>grouped[levelTier(m)].push(m));const sections=['A','B','C'].filter(l=>grouped[l].length).map(l=>`<div class="level-group"><p class="level-group-head">Level ${l}</p>${grouped[l].map(renderCourtCard).join('')}</div>`).join('');return `<div class="carousel-panel${i===0?' active':''}" data-panel="${t.key}">${sections}</div>`}).join('');return `<div class="carousel-tabs">${tabs}</div><div class="carousel-track">${panels}</div>`}
function bindCarousel(){$$('[data-carousel-tab]').forEach(tab=>tab.onclick=()=>{$$('.carousel-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');$$('.carousel-panel').forEach(p=>p.classList.remove('active'));const panel=$(`[data-panel="${tab.dataset.carouselTab}"]`);if(panel)panel.classList.add('active')})}
function renderOccupiedCourt(c,o){const side=t=>`<div class="team">${t.map(x=>`<strong>${nameOf(x.id)}</strong>`).join('')}<small>${t.map(x=>x.level).join('')}</small></div>`;return `<article class="court-card live-court"><div class="court-head"><div><strong>Court ${c}</strong> <span class="court-type">${o.type} · LIVE</span></div><button type="button" class="court-edit" data-recourt="${c}" aria-label="Change Court ${c} lineup">✎</button></div><div class="teams">${side(o.teamA)}<span class="versus">VS</span>${side(o.teamB)}</div><p class="why">${elapsed(o.startedAt)}</p><button class="played" data-end="${c}">End round · +1 all</button><button type="button" class="court-clear" data-clear="${c}">Clear without logging</button></article>`}
function renderEmptyCourt(c){return `<article class="court-card empty-court"><div class="court-head"><div><strong>Court ${c}</strong> <span class="court-type">FREE</span></div></div><p class="why">Nobody on this court yet.</p><button class="played" data-fill="${c}">Pick 4 players</button></article>`}
function renderCourts(){const s=state.session;const out=[];for(let c=1;c<=s.courts;c++){const o=s.courtState[c];out.push(o?renderOccupiedCourt(c,o):renderEmptyCourt(c))}$('#courts').innerHTML=out.join('');const live=Object.keys(s.courtState).length;$('#courts-note').textContent=`${live} of ${s.courts} in play · ${s.rounds.length} round${s.rounds.length===1?'':'s'} logged`;$$('[data-fill]').forEach(b=>b.onclick=()=>openLineupDialog([],Number(b.dataset.fill)));$$('[data-recourt]').forEach(b=>b.onclick=()=>{const c=Number(b.dataset.recourt);const o=s.courtState[c];openLineupDialog([...o.teamA,...o.teamB].map(p=>p.id),c)});$$('[data-end]').forEach(b=>b.onclick=()=>endRound(Number(b.dataset.end)));$$('[data-clear]').forEach(b=>b.onclick=()=>clearCourt(Number(b.dataset.clear)))}
function startCourt(court,ids,partition){const roster=state.session.roster;const four=ids.map(id=>roster.find(x=>x.playerId===id)).filter(Boolean);if(four.length!==4)return;const[ia,ib]=PARTITIONS[partition%3];const snap=p=>({id:p.playerId,level:p.level,gender:p.gender});const prior=state.session.courtState[court];state.session.courtState[court]={teamA:ia.map(i=>snap(four[i])),teamB:ib.map(i=>snap(four[i])),type:lineupType(four),startedAt:prior?prior.startedAt:Date.now()};saveSession();renderLive();toast(`Court ${court} started`)}
function clearCourt(court){const o=state.session.courtState[court];if(!o)return;delete state.session.courtState[court];saveSession();renderLive();toast(`Court ${court} cleared · no counts changed`,()=>{state.session.courtState[court]=o;saveSession();renderLive()})}
function endRound(court){const s=state.session;const o=s.courtState[court];if(!o)return;const ids=[...o.teamA,...o.teamB].map(p=>p.id);const before=ids.map(id=>({id,count:s.roster.find(x=>x.playerId===id).count}));const round={id:crypto.randomUUID(),court,type:o.type,teamA:o.teamA,teamB:o.teamB,startedAt:o.startedAt,endedAt:Date.now()};s.rounds.push(round);delete s.courtState[court];ids.forEach(id=>{const r=s.roster.find(x=>x.playerId===id);r.count++;r.lastUpdated=Date.now()});saveSession();renderLive();toast(`Court ${court} logged · +1 all`,()=>{s.rounds=s.rounds.filter(r=>r.id!==round.id);s.courtState[court]=o;before.forEach(x=>s.roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()})}
function logLooseRound(ids,partition){const s=state.session;const four=ids.map(id=>s.roster.find(x=>x.playerId===id)).filter(Boolean);if(four.length!==4)return;const[ia,ib]=PARTITIONS[partition%3];const snap=p=>({id:p.playerId,level:p.level,gender:p.gender});const round={id:crypto.randomUUID(),court:null,type:lineupType(four),teamA:ia.map(i=>snap(four[i])),teamB:ib.map(i=>snap(four[i])),startedAt:Date.now(),endedAt:Date.now()};const before=four.map(p=>({id:p.playerId,count:p.count}));s.rounds.push(round);four.forEach(p=>{p.count++;p.lastUpdated=Date.now()});saveSession();renderLive();toast('Round logged · +1 all',()=>{s.rounds=s.rounds.filter(r=>r.id!==round.id);before.forEach(x=>s.roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()})}
function renderLive(avoid){setView('live-view');const s=state.session;$('#live-courts').textContent=`${s.courts} court${s.courts===1?'':'s'}`;$('#session-title').textContent=new Date(s.startedAt).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'short'});$('#summary').innerHTML=summary().map(x=>`<div class="summary-item"><strong>${x.v}</strong><span>${x.l}</span></div>`).join('');renderCourts();const free=emptyCourts();const busy=busyIds();const avail=s.roster.map(p=>busy.has(p.playerId)?{...p,status:'benched'}:p);const rec=recommend(avail,Math.max(1,free.length),typeCounts(),avoid||new Set());s.lastRecommendation=rec;saveSession();const upNext=free.length?'':'<p class="muted" style="margin:0 0 10px">All courts busy — here’s who’s up next.</p>';$('#recommendations').innerHTML=upNext+renderCarousel(rec);bindCarousel();$$('[data-start]').forEach(b=>b.onclick=()=>{const m=rec.matches.find(x=>x.court===Number(b.dataset.start));const target=emptyCourts()[0];if(!m||!target)return;b.disabled=true;startCourt(target,[...m.teamA,...m.teamB].map(p=>p.playerId),0)});$$('[data-edit-court]').forEach(b=>b.onclick=()=>{const m=rec.matches.find(x=>x.court===Number(b.dataset.editCourt));openLineupDialog(m?[...m.teamA,...m.teamB].map(p=>p.playerId):[],emptyCourts()[0]??null)});const wait=[...rec.waiting,...rec.incomplete];$('#waiting').innerHTML=wait.length?`<strong>Waiting (${wait.length})</strong><br>${wait.map(p=>p.name).join(' · ')}${rec.incomplete.length?'<br><small>Incomplete players are not eligible until corrected.</small>':''}`:'';renderLedger()}

function statsBlock(p,st){st=st||playerStats(p.playerId);if(!st.n)return '<div class="player-stats"><p class="muted" style="margin:0">No rounds logged yet — start a court to build this player\u2019s history.</p></div>';const roles=['carry','intensity','light'].map(k=>`<span class="chip chip-${k}">${ROLE_LABEL[k]} ×${st.roles[k]}</span>`).join('');const tiers=['A','B','C'].map(k=>`<span class="chip chip-lv chip-lv-${k}">${k} ×${st.tiers[k]}</span>`).join('');const drift=p.count!==st.n?`<p class="stat-note">Ledger says ${p.count}; ${st.n} round${st.n===1?'':'s'} logged (rest were manual adjustments).</p>`:'';return `<div class="player-stats"><div class="stat-line"><span class="stat-label">Role mix</span><span class="chips">${roles}</span></div><div class="stat-line"><span class="stat-label">Level mix</span><span class="chips">${tiers}</span></div>${drift}</div>`}
function playerRow(p){const oc=courtOf(p.playerId);const open=state.openCards.has(p.playerId);const benched=p.status==='benched';const st=playerStats(p.playerId);const glance=st.n?`<div class="role-glance">${['carry','intensity','light'].map(k=>`<span class="chip chip-${k} chip-mini" title="${ROLE_LABEL[k]} ×${st.roles[k]}">${ROLE_LABEL[k][0]}${st.roles[k]}</span>`).join('')}</div>`:'';return `<div class="player-block${open?' open':''}"><div class="player-row ${benched?'benched':''}${oc?' on-court':''}"><div class="player-meta"><button type="button" class="name-btn" data-card="${p.playerId}" aria-expanded="${open}">${p.name}${oc?` <span class="oncourt-badge">Court ${oc}</span>`:''}</button><small>${p.gender} · <button type="button" class="grade-btn grade-${p.level}" data-grade="${p.playerId}" aria-label="Change ${p.name} level (now ${p.level})">${p.level}</button>${p.lastUpdated?` · ${timeAgo(p.lastUpdated)}`:''}</small>${glance}</div><div class="row-actions"><div class="count-controls"><button data-count="${p.playerId}" data-delta="-1" aria-label="Subtract one game from ${p.name}">−</button><output aria-label="${p.name} has played ${p.count} games">${p.count}</output><button data-count="${p.playerId}" data-delta="1" aria-label="Add one game to ${p.name}">+</button></div><button type="button" class="bench-icon${benched?' is-benched':''}" data-bench="${p.playerId}" aria-label="${benched?'Return':'Bench'} ${p.name}" title="${benched?'Return to play':'Bench (sit out)'}">${benched?'▶':'⏸'}</button></div></div>${open?statsBlock(p,st):''}</div>`}
function cycleGrade(id){const grades=['A','B','C'];const p=state.session.roster.find(x=>x.playerId===id);if(!p)return;const oldLevel=p.level;const next=grades[(grades.indexOf(p.level)+1)%3];p.level=next;p.lastUpdated=Date.now();const cached=state.players.find(x=>x.id===id);if(cached)cached.level=next;cachePlayers(state.players);saveSession();renderLive();toast(`${p.name} → Level ${next}`);if(!state.demo){api(`/api/players/${id}`,{method:'PATCH',body:JSON.stringify({level:next})}).catch(()=>toast(`${p.name} level saved locally · Notion sync failed`))}}
function renderLedger(){const q=$('#ledger-search').value.trim().toLowerCase();const rows=[...state.session.roster].filter(p=>p.name.toLowerCase().includes(q)).sort((a,b)=>a.count-b.count||a.name.localeCompare(b.name));const playing=rows.filter(p=>p.status!=='benched'),benched=rows.filter(p=>p.status==='benched');$('#ledger').innerHTML=(playing.length?`<div class="ledger-group"><p class="ledger-group-head">Playing (${playing.length})</p>${playing.map(playerRow).join('')}</div>`:(q?'<p class="muted">No players match.</p>':''))+(benched.length?`<details class="ledger-group"${playing.length?'':' open'}><summary class="ledger-group-head">Benched (${benched.length})</summary>${benched.map(playerRow).join('')}</details>`:'');$$('[data-count]').forEach(b=>b.onclick=()=>adjustCount(b.dataset.count,Number(b.dataset.delta)));$$('[data-bench]').forEach(b=>b.onclick=()=>toggleBench(b.dataset.bench));$$('[data-grade]').forEach(b=>b.onclick=()=>cycleGrade(b.dataset.grade));$$('[data-card]').forEach(b=>b.onclick=()=>{const id=b.dataset.card;state.openCards.has(id)?state.openCards.delete(id):state.openCards.add(id);renderLedger()})}
function adjustCount(id,d){const p=state.session.roster.find(x=>x.playerId===id);p.count=Math.max(0,p.count+d);p.lastUpdated=Date.now();saveSession();renderLive()}
function toggleBench(id){const p=state.session.roster.find(x=>x.playerId===id);p.status=p.status==='benched'?'playing':'benched';saveSession();renderLive()}
function playedIds(ids){const roster=state.session.roster;const before=ids.map(id=>({id,count:roster.find(x=>x.playerId===id).count}));ids.forEach(id=>{const r=roster.find(x=>x.playerId===id);r.count++;r.lastUpdated=Date.now()});saveSession();renderLive();toast('Four counts updated',()=>{before.forEach(x=>roster.find(p=>p.playerId===x.id).count=x.count);saveSession();renderLive()})}
function played(match,button){if(!match||button.disabled)return;button.disabled=true;playedIds(match.players.map(p=>p.playerId))}

function openLineupDialog(prefillIds,court){state.lineupSelected=new Set(prefillIds);state.lineupCourt=court??null;state.lineupPartition=0;$('#lineup-dialog-title').textContent=court?`Court ${court} lineup`:'Log a round';$('#lineup-search').value='';$('#lineup-error').textContent='';renderLineupPicker();$('#lineup-dialog').showModal()}
function renderLineupPicker(){const q=$('#lineup-search').value.trim().toLowerCase();const busy=busyIds();const eligible=state.session.roster.filter(p=>p.status!=='benched'&&p.name.toLowerCase().includes(q)&&(!busy.has(p.playerId)||state.lineupSelected.has(p.playerId)||courtOf(p.playerId)===state.lineupCourt)).sort((a,b)=>{const ab=busy.has(a.playerId)?1:0,bb=busy.has(b.playerId)?1:0;return ab-bb||a.count-b.count||(a.lastUpdated??0)-(b.lastUpdated??0)||a.name.localeCompare(b.name)});$('#lineup-picker').innerHTML=eligible.map(p=>`<button type="button" class="picker ${state.lineupSelected.has(p.playerId)?'selected':''}" data-lineup-pick="${p.playerId}" aria-pressed="${state.lineupSelected.has(p.playerId)}"><span class="avatar">${initials(p.name)}</span><span><strong>${p.name}</strong><small>${p.gender||'Gender missing'} · ${p.level?`Level ${p.level}`:'Level missing'} · ${p.count} played</small></span></button>`).join('')||'<p class="muted">No players available.</p>';$$('[data-lineup-pick]').forEach(b=>b.onclick=()=>{const id=b.dataset.lineupPick;if(state.lineupSelected.has(id))state.lineupSelected.delete(id);else{if(state.lineupSelected.size>=4){toast('Only 4 players can play a court');return}state.lineupSelected.add(id)}renderLineupPicker()});$('#lineup-count').textContent=`${state.lineupSelected.size} of 4 selected`;renderLineupTeams();const ready=state.lineupSelected.size===4;$('#lineup-confirm').disabled=!ready;$('#lineup-confirm').textContent=state.lineupCourt?`Start on Court ${state.lineupCourt}`:'Log round · +1 all'}
function renderLineupTeams(){const box=$('#lineup-teams');if(state.lineupSelected.size!==4){box.hidden=true;box.innerHTML='';return}box.hidden=false;const four=[...state.lineupSelected].map(id=>state.session.roster.find(p=>p.playerId===id));const[ia,ib]=PARTITIONS[state.lineupPartition%3];const type=lineupType(four);const side=idx=>`<div class="lineup-side">${idx.map(i=>`<strong>${four[i].name}</strong>`).join('')}<small>${idx.map(i=>four[i].level).join('')}</small></div>`;box.innerHTML=`<div class="lineup-teams-head"><span class="court-type">${type}</span><button type="button" id="swap-teams" class="text-button">⇄ Swap pairing</button></div><div class="lineup-teams-row">${side(ia)}<span class="versus">VS</span>${side(ib)}</div>${type==='MIX'?'<p class="stat-note">Uneven gender mix — allowed, but not MD, WD, or XD.</p>':''}`;$('#swap-teams').onclick=()=>{state.lineupPartition=(state.lineupPartition+1)%3;renderLineupTeams()}}


function openPlayerDialog(player=null){$('#player-dialog-title').textContent=player?'Edit player':'Add player';$('#edit-player-id').value=player?.id||'';$('#player-name').value=player?.name||'';$('#player-gender').value=player?.gender||'';$('#player-level').value=player?.level||'';$('#player-error').textContent='';$('#player-dialog').showModal()}
async function savePlayer(e){e.preventDefault();const id=$('#edit-player-id').value;const input={name:$('#player-name').value.trim(),gender:$('#player-gender').value,level:$('#player-level').value};if(!input.name||!input.gender||!input.level){$('#player-error').textContent='Name, Gender, and Level are required.';return}const dup=state.players.find(p=>p.id!==id&&p.name.trim().toLowerCase()===input.name.toLowerCase());if(dup&&!confirm(`${dup.name} already exists. Create another player with this name?`))return;$('#save-player').disabled=true;try{let saved;if(state.demo){saved={id:id||crypto.randomUUID(),...input,active:true,incomplete:false}}else saved=await api(id?`/api/players/${id}`:'/api/players',{method:id?'PATCH':'POST',body:JSON.stringify(input)});const i=state.players.findIndex(p=>p.id===saved.id);if(i>=0)state.players[i]=saved;else state.players.push(saved);cachePlayers(state.players);if(state.session){const existing=state.session.roster.find(p=>p.playerId===saved.id);if(existing){Object.assign(existing,{name:saved.name,gender:saved.gender,level:saved.level})}else state.session.roster.push({playerId:saved.id,name:saved.name,gender:saved.gender,level:saved.level,count:minActiveCount(),status:'playing',lastUpdated:Date.now()});saveSession();renderLive()}else{state.selected.add(saved.id);renderSetupMeta()}$('#player-dialog').close();toast(id?'Player updated':'Player added')}catch(err){$('#player-error').textContent=err.message}finally{$('#save-player').disabled=false}}
async function boot(){const s=read(SESSION);if(validSession(s)){state.session=migrateSession(s);saveSession();renderLive();return}if(!cfg()){setView('connect-view');return}try{await loadPlayers();showSetup()}catch{const cached=read(CACHE);if(cached?.players){state.players=cached.players;showSetup();toast('Offline · using saved players')}else setView('connect-view') }}

$('#connect').onclick=async()=>{const url=$('#worker-url').value.trim(),key=$('#app-key').value.trim();if(!url||!key)return;write(CFG,{url,key});try{await loadPlayers();showSetup()}catch(e){localStorage.removeItem(CFG);$('#connect-error').textContent=e.message}};
$('#demo').onclick=async()=>{state.demo=true;await loadPlayers();showSetup()};
$('#player-search').oninput=renderPicker;$('#ledger-search').oninput=renderLedger;$$('[data-court-delta]').forEach(b=>b.onclick=()=>{state.setupCourts=Math.max(1,Math.min(10,state.setupCourts+Number(b.dataset.courtDelta)));renderSetupMeta()});$$('[data-live-court-delta]').forEach(b=>b.onclick=()=>{const s=state.session;const next=Math.max(1,Math.min(10,s.courts+Number(b.dataset.liveCourtDelta)));const stranded=Object.keys(s.courtState).map(Number).filter(c=>c>next);if(stranded.length&&!confirm(`Court ${stranded.join(', ')} still has players on it. Remove the court and clear them without logging?`))return;stranded.forEach(c=>delete s.courtState[c]);s.courts=next;saveSession();renderLive();if(stranded.length)toast(`Court ${stranded.join(', ')} cleared · no counts changed`)});
$('#start-session').onclick=startSession;$('#new-session').onclick=newSession;$('#open-add-player').onclick=()=>openPlayerDialog();$('#live-add-player').onclick=()=>openPlayerDialog();$('#refresh-recommendation').onclick=()=>{const prev=state.session.lastRecommendation;const before=recKey(prev);const avoid=new Set((prev?.matches||[]).flatMap(m=>[m.players.map(p=>p.playerId).sort().join('|')]));renderLive(avoid);const after=recKey(state.session.lastRecommendation);toast(before===after?'Refreshed · that\'s the fairest option available right now':'Refreshed · new match-up')};$('#log-custom-match').onclick=()=>openLineupDialog([],null);$('#lineup-search').oninput=renderLineupPicker;$('#lineup-confirm').onclick=()=>{if(state.lineupSelected.size!==4){$('#lineup-error').textContent='Pick exactly 4 players.';return}const ids=[...state.lineupSelected],part=state.lineupPartition,court=state.lineupCourt;$('#lineup-dialog').close();if(court)startCourt(court,ids,part);else logLooseRound(ids,part)};$('#player-form').addEventListener('submit',savePlayer);$$('[data-close-dialog]').forEach(b=>b.onclick=()=>{$('#player-dialog').close();$('#lineup-dialog').close()});
setInterval(()=>{if(state.session&&!$('#live-view').hidden){renderCourts();renderLedger()}},30000);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
boot();