name = "netflick-proxy"
main = "worker.js"
compatibility_date = "2026-07-01"

[vars]
ALLOWED_ORIGIN = "https://merrickjo.github.io"

# Set once from this folder:
# wrangler secret put APP_KEY

[[d1_databases]]
binding = "DB"
database_name = "netflick-db"
database_id = "39af4ef8-afe7-4c05-9f76-178212372b17"
